about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from scrapbook.views import (
    custom_page_not_found_view,
    custom_permission_denied_view,
    custom_error_view,
    custom_bad_request_view,
)

# Custom error handlers
handler404 = custom_page_not_found_view
handler500 = custom_error_view
handler403 = custom_permission_denied_view
handler400 = custom_bad_request_view

urlpatterns = [
    path('about/', include("about.urls")),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('scrapbook/', include(('scrapbook.urls', 'scrapbook'),
                               namespace='scrapbook')),
    path('summernote/', include('django_summernote.urls')),
    path("", include("scrapbook.urls"), name='scrapbook-urls'),
]

scrapbook/urls.py
from django.urls import path
from . import views

# Custom error handlers
handler403 = 'scrapbook.views.custom_permission_denied_view'

# URL patterns for the scrapbook app
urlpatterns = [
    path('trigger-403-error/', views.trigger_403_error, name='trigger-403-error'),
    path('trigger-500-error/', views.trigger_500_error, name='trigger-500-error'),
    path("", views.ScrapbookListView.as_view(), name="home"),
    path("my-scrapbooks/", views.ScrapbookMyListView.as_view(), name="my_scrapbook_list"),
    path("shared-scrapbooks/", views.ScrapbookSharedListView.as_view(), name="shared_scrapbook_list"),
    path('share/', views.ShareContentView.as_view(), name='share_content'),
    path('create-scrapbook/', views.ScrapbookCreateView.as_view(), name="create-scrapbook"),
    path('<slug:slug>/', views.ScrapbookDetailView.as_view(), name='scrapbook_detail'),
    path('shared/<slug:slug>/', views.ScrapbookSharedDetailView.as_view(), name='shared_scrapbook_detail'),
    path('<slug:slug>/edit-scrapbook/<int:scrapbook_id>/', views.ScrapbookUpdateView.as_view(), name='edit-scrapbook'),
    path('<slug:slug>/delete-scrapbook/<int:scrapbook_id>/', views.ScrapbookDeleteView.as_view(), name="delete-scrapbook"),
    path('<slug:scrapbook_slug>/create-post/', views.PostCreateView.as_view(), name='create-post'),
    path('<slug:scrapbook_slug>/edit-post/<int:post_id>/', views.PostUpdateView.as_view(), name='edit-post'),
    path('<slug:scrapbook_slug>/delete-post/<int:post_id>/', views.PostDeleteView.as_view(), name='delete-post'),
    path('<slug:scrapbook_slug>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
]

scrapbook/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import generic, View
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.decorators.csrf import requires_csrf_token
from .models import Scrapbook, Post, SharedAccess
from .forms import PostForm, ScrapbookForm, ShareContentForm


class ScrapbookListView(generic.ListView):
    """
    View for displaying all public scrapbooks.

    Attributes:
    model -- The Scrapbook model.
    ordering -- The order in which the scrapbooks are displayed.
    template_name -- The template used to render the view.
    paginate_by -- The number of scrapbooks displayed per page.

    Methods:
    get_queryset -- Filter scrapbooks to only show public scrapbooks.
    get_context_data -- Add the number of posts in each scrapbook to the
    context.

    Template:
    scrapbook/index.html
    """
    model = Scrapbook
    ordering = ["-created_on"]
    template_name = "scrapbook/index.html"
    paginate_by = 6  # Show 6 scrapbooks per page

    def get_queryset(self):
        # Filter scrapbooks to only show public scrapbooks
        queryset = Scrapbook.objects.filter(status=2).order_by('-created_on')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = Post.objects.filter(
            scrapbook__in=self.get_queryset(), status=2).count()
        return context


class ScrapbookMyListView(LoginRequiredMixin, generic.ListView):
    """
    View for displaying the user's scrapbooks.

    Attributes:
    model -- The Scrapbook model.
    ordering -- The order in which the scrapbooks are displayed.
    template_name -- The template used to render the view.
    paginate_by -- The number of scrapbooks displayed per page.
    login_url -- The URL to redirect to if the user is not logged in.

    Methods:
    get_queryset -- Filter scrapbooks to only show the user's scrapbooks.
    get_context_data -- Add the number of posts in each scrapbook to the
    context.

    Template:
    scrapbook/scrapbook_mylist.html
    """
    model = Scrapbook
    ordering = ["-created_on"]
    template_name = "scrapbook/scrapbook_mylist.html"
    paginate_by = 6  # Show 6 scrapbooks per page
    login_url = '/accounts/login/'

    def get_queryset(self):
        # Filter scrapbooks to only show the user's scrapbooks
        queryset = Scrapbook.objects.filter(
            author=self.request.user).order_by('-created_on')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = Post.objects.filter(
            scrapbook__in=self.get_queryset(), status=2).count()
        return context


class ScrapbookSharedListView(LoginRequiredMixin, generic.ListView):
    """
    View for displaying the user's shared scrapbooks.

    Attributes:
    model -- The Scrapbook model.
    ordering -- The order in which the scrapbooks are displayed.
    template_name -- The template used to render the view.
    paginate_by -- The number of scrapbooks displayed per page.
    login_url -- The URL to redirect to if the user is not logged in.

    Methods:
    get_queryset -- Filter scrapbooks to only show the shared scrapbooks.
    get_context_data -- Add the number of posts in each scrapbook to the
    context.

    Template:
    scrapbook/scrapbook_sharedlist.html
    """
    model = Scrapbook
    ordering = ["-created_on"]
    template_name = "scrapbook/scrapbook_sharedlist.html"
    paginate_by = 6  # Show 6 scrapbooks per page
    login_url = '/accounts/login/'

    def get_queryset(self):
        # Filter scrapbooks to only show the shared scrapbooks
        queryset = Scrapbook.objects.filter(
            sharedaccess__user=self.request.user).distinct()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = Post.objects.filter(
            scrapbook__in=self.get_queryset(), status=2).count()
        return context


class ScrapbookDetailView(generic.DetailView):
    """
    View for displaying a scrapbook and its posts.

    Attributes:
    model -- The Scrapbook model.
    template_name -- The template used to render the view.

    Methods:
    get_object -- Get the scrapbook object.
    handle_no_permission -- Handle cases where the user does not have
    permission to view the scrapbook.
    get_context_data -- Add the posts in the scrapbook to the context.

    Template:
    scrapbook/scrapbook_detail.html
    """
    model = Scrapbook
    template_name = 'scrapbook/scrapbook_detail.html'

    def get_object(self, queryset=None):
        scrapbook = super().get_object(queryset)
        user = self.request.user
        if (
            scrapbook.status != 2 and
            (not user.is_authenticated or scrapbook.author != user)
        ):
            if (
                not user.is_authenticated or
                not SharedAccess.objects.filter(
                    user=user,
                    scrapbook=scrapbook).exists()
            ):
                raise PermissionDenied(
                    "You do not have permission to view this scrapbook.")
        return scrapbook

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return redirect('account_login')
        return HttpResponseForbidden(
            "You do not have permission to view this scrapbook.")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        scrapbook = self.get_object()
        posts = scrapbook.posts.all()
        paginator = Paginator(posts, 6)  # Show 6 posts per page

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        ordering = ["-created_on"]

        # Get shared access for the current user and scrapbook
        sharedaccess = False
        if self.request.user.is_authenticated:
            sharedaccess = SharedAccess.objects.filter(
                user=self.request.user, scrapbook=scrapbook).exists()

        context.update({
            'scrapbook': scrapbook,
            'page_obj': page_obj,
            'posts': page_obj.object_list,
            'is_paginated': page_obj.has_other_pages(),
            'ordering': ordering,
            'sharedaccess': sharedaccess,
        })
        return context


def handle_post_request(request, scrapbook):
    post_form = PostForm(request.POST, request.FILES)
    if post_form.is_valid():
        post = post_form.save(commit=False)
        post.author = request.user
        post.scrapbook = scrapbook
        post.save()
        messages.success(request, "Post created successfully.")
    else:
        messages.error(request, "Post creation failed.")
    return redirect(reverse(
        'scrapbook:scrapbook_detail', kwargs={'slug': scrapbook.slug}))


class ScrapbookCreateView(LoginRequiredMixin, CreateView):
    """
    View for creating a new scrapbook.

    Attributes:
    model -- The Scrapbook model.
    form_class -- The form used to create the scrapbook.
    template_name -- The template used to render the view.
    login_url -- The URL to redirect to if the user is not logged in.

    Methods:
    form_valid -- Set the author of the scrapbook to the current user.
    get_success_url -- Redirect to the detail view of the created scrapbook.
    get_context_data -- Add the action to the context.

    Template:
    scrapbook/scrapbook_form.html
    """
    model = Scrapbook
    form_class = ScrapbookForm
    template_name = 'scrapbook/scrapbook_form.html'
    login_url = '/accounts/login/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, "Scrapbook created successfully.")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'scrapbook:scrapbook_detail', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'create'
        return context


class ScrapbookUpdateView(LoginRequiredMixin, UpdateView):
    """
    View for updating a scrapbook.

    Attributes:
    model -- The Scrapbook model.
    form_class -- The form used to update the scrapbook.
    template_name -- The template used to render the view.
    login_url -- The URL to redirect to if the user is not logged in.

    Methods:
    form_valid -- Display a success message when the form is valid.
    get_success_url -- Redirect to the user's scrapbook list.
    get_context_data -- Add the action to the context.

    Template:
    scrapbook/scrapbook_form.html
    """
    model = Scrapbook
    form_class = ScrapbookForm
    template_name = 'scrapbook/scrapbook_form.html'
    login_url = '/accounts/login/'

    def form_valid(self, form):
        messages.success(self.request, "Scrapbook updated successfully.")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('my_scrapbook_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'edit'
        return context


class ScrapbookDeleteView(LoginRequiredMixin, DeleteView):
    """
    View for deleting a scrapbook.

    Attributes:
    model -- The Scrapbook model.

scrapbook/templates/scrapbook/confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}Delete Confirmation{% endblock %}
    
{% block content %}
<div class="container move-up">
    <div class="row">
        <div class="col-12 col-lg-8 mx-auto">
            <h3>
                Confirm Delete <i class="fa-regular fa-trash-can"></i>
            </h3>
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete "<strong>{{ object }}</strong>"?</p>
                {{ form }}
                <div class="col-sm-12 col-md-6 col-lg-4 text-start mb-1 pb-4">
                    <input class="btn btn-info" type="submit" value="Confirm" aria-label="Confirm the Delete">
                    <a class="btn btn-secondary" href="javascript:history.back()" aria-label="Cancel Delete and go back a page">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

scrapbook/templates/scrapbook/post_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
    
{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input class="btn btn-info" type="submit" value="Confirm">
    </form>
</div>
{% endblock content %}

scrapbook/templates/scrapbook/post_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{% if action == 'create' %}Create{% else %}Edit{% endif %} Post Form{% endblock %}

{% block content %}
<div class="container move-up">
    <div class="row">
        <div class="col-12 col-lg-8 mx-auto">
            <h3>
                {% if action == 'create' %}
                    Create Post Content
                {% else %}
                    Edit Post Content
                {% endif %} <i class="fa-regular fa-pen-to-square"></i>
            </h3>
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Feedback to user on scrapbook to be changed -->
            <p>You want to {% if action == 'create' %}add{% else %}edit{% endif %} a post in the scrapbook, <strong>{{ scrapbook.title }}</strong>.</p>
            <!-- Render the form fields with crispy -->
            {{ form|crispy }}
            <!-- Current image preview -->
            <div class="mb-3 current-image">
                {% if action == 'create' %}
                <img id="current-image-preview" src="{% static 'images/thumbnail.jpg' %}" alt="Placeholder preview of Post Image">
                {% elif action == 'edit' and form.instance.image %}
                <img id="current-image-preview" src="{{ form.instance.image.url }}" alt="Thumbnail preview of Post Image">
                {% endif %}
            </div>
            <!-- Submit button -->
            <div class="col-sm-12 col-md-6 col-lg-4 text-start mb-1 pb-4">
                <input class="btn btn-info" type="submit" value="{% if action == 'create' %}Add{% else %}Update{% endif %}" aria-label="Update Post Button">
                <a class="btn btn-secondary" href="javascript:history.back()" aria-label="Cancel {% if action == 'create' %}Create{% else %}Edit{% endif %} and go back a page">Cancel</a>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/thumbnail-image.js' %}"></script>
{% endblock extra_js %}

scrapbook/templates/scrapbook/scrapbook_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Scrapbook Detail{% endblock %}

{% block content %}
<div class="container with-backbtn">
    <div class="row">
        <div class="col-12 mt-3">
            <!-- Back to Scrapbook List -->
            <a href="javascript:history.back()" class="btn btn-info" aria-label="Go back to previous page"><i class="fa-solid fa-arrow-left"></i></a>
            <br>
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-8 mt-1 pt-3 ">
                    <!-- Scrapbook title -->
                    <div class="col-sm-12 col-md-6">
                        <h3>{{ scrapbook.title }}</h3>
                    </div>
                    <!-- Scrapbook author | the scrapbook's created date goes after -->
                    <div class="col-12">
                        <p class="scrapbook-subtitle d-inline">{{ scrapbook.author }} | </p>
                        <p class="scrapbook-subtitle d-inline">created on: {{ scrapbook.created_on }}</p>
                    </div>
                    <!-- Filter to mark content as safe for rendering as HTML -->
                    <div class="d-grid gap-2 d-md-block mb-1">
                        <p>{{ scrapbook.content | safe }}</p>
                        <!-- Show note-to-self and Add Post button if user is the author -->
                        {% if user.is_authenticated and scrapbook.author == user %}
                            {% if not scrapbook.description == "" %}
                            <p id="description">Note to Self: {{ scrapbook.description | safe }}</p>
                            {% endif %}
                        <a href="{% url 'create-post' scrapbook.slug %}" class="btn btn-info scrapbook-link" aria-label="Go to Create Post page">Add a new Post <i class="fa-regular fa-plus"></i></a>
                        {% endif %}
                    </div>
                </div>
                <!-- Edit and Delete Buttons -->
                <div class="col-sm-12 col-md-2 col-lg-4 text-center mb-1 pb-4">
                    {% if user.is_authenticated and scrapbook.author == user %}
                        <a href="{% url 'edit-scrapbook' scrapbook.slug scrapbook.id %}" class="btn btn-info btn-edit scrapbook-link mx-auto my-2" aria-label="Go to Edit Scrapbook page">Edit <i class="fa-regular fa-pen-to-square"></i></a>
                        <a href="{% url 'delete-scrapbook' scrapbook.slug scrapbook.id %}" class="btn btn-danger scrapbook-link mx-auto my-2" aria-label="Go to Delete Scrapbook page">Delete <i class="fa-regular fa-trash-can"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- Post Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% if not sharedaccess and scrapbook.author != user and scrapbook.status != 2 %}
                <div class="col-12">
                    <div class="alert alert-danger" role="alert">
                        You do not have permission to view this scrapbook.
                    </div>
                </div>
                {% else %}
                    {% for post in posts %}
                    <!-- add cards for each post in this scrapbook -->
                    <!-- don't show a post if its status is not Public and its author is not the logged-in user -->
                    <div id="post{{ post.id }}" class="col-md-6 col-lg-4 {% if not post.status == 2 and not post.author == user %}d-none{% endif %}" data-title="{{ post.title }}" data-content="{{ post.content }}" data-image-url="{% if post.images.all %}{{ post.images.all.0.featured_image.url }}{% endif %}">
                        <div class="card shadow-sm mb-4" role="tablist">
                            <div class="text-center">
                                <img class="card-img-top {% if user.is_authenticated and post.author == user and post.status == 0 %}opacity-50{% endif %}" src="{{ post.image.url}}" alt="Image for the post titled '{{post.title}}'">
                            </div>
                            <div class="card-header collapsible cursor-pointer collapsed" data-bs-toggle="collapse" data-bs-target="#card-collapsible-{{ post.id }}" aria-controls="card-collapsible-{{ post.id }}" aria-expanded="false" id="heading-collapsed-{{ post.id }}" role="tab">
                                <div class="card-title d-inline">
                                    <!-- if logged in user is the post author, make the title a link -->
                                    {% if user.is_authenticated %}
                                        {% if post.author == user or sharedaccess %}
                                        <a class="text-decoration-none" href="{% url 'scrapbook:post_detail' scrapbook.slug post.slug %}" aria-label="Go to Post Detail page">
                                        {% endif %}   
                                    {% endif %}                                 
                                    <h5 class="card-title d-inline {% if user.is_authenticated and post.author == user %}linked-title{% endif %}">{{ post.title }}</h5>
                                    {% if user.is_authenticated %}
                                        {% if post.author == user or sharedaccess %}
                                        </a>
                                        {% endif %}
                                    {% endif %}
                                    <!-- Status icon conditionals -->
                                    {% if post.status == 0 %}
                                    <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-pen"></i></div>
                                    {% elif post.status == 1 %}
                                    <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-lock"></i></div>
                                    {% elif post.status == 2 %}
                                    <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-globe"></i></div>
                                    {% endif %}
                                </div>
                                <div class="card-toolbar d-inline float-end">
                                    <i class="fa fa-chevron-down pull-right ms-auto"></i>
                                </div>
                            </div>
                            <div id="card-collapsible-{{ post.id }}" class="collapse" aria-labelledby="heading-collapsed-{{ post.id }}">
                                <div class="card-body px-3">
                                    <div class="{% if user.is_authenticated and post.author == user and post.status == 0 %}opacity-50{% endif %}">
                                        <!-- Last Updated -->
                                        <p class="card-subtitle date-time mb-2">Updated: {{ post.updated_on }}</p>
                                        <p class="card-text">{{ post.content|truncatechars:72|safe }}</p>
                                    </div>
                                    <div>
                                        <!-- Open, Edit and Delete Buttons -->
                                        <div class="d-grid gap-2 d-md-block text-center mb-1">
                                            <a href="{% url 'scrapbook:post_detail' scrapbook.slug post.slug %}" class="btn btn-info scrapbook-link" aria-label="Go to Post Detail page">Open <i class="fa-regular fa-image"></i></a>
                                            <!-- if logged in user is the post author, show edit and delete buttons -->
                                            {% if user.is_authenticated and post.author == user %}
                                                <a href="{% url 'edit-post' scrapbook.slug post.id %}" class="btn btn-info btn-edit scrapbook-link" aria-label="Go to Edit Post page">Edit <i class="fa-regular fa-pen-to-square"></i></a>
                                                <a href="{% url 'delete-post' scrapbook.slug post.id %}" class="btn btn-danger scrapbook-link" aria-label="Go to Delete Post page">Delete <i class="fa-regular fa-trash-can"></i></a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                        {% if forloop.counter|divisibleby:6 %}
                            </div>
                            <div class="row">
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Pagination -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Go to previous page"> &laquo; PREV</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Go to next page"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock content %}

scrapbook/templates/scrapbook/scrapbook_shareddetail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Scrapbook Detail{% endblock %}

{% block content %}
<div class="container with-backbtn">
    <div class="row">
        <div class="col-12 mt-3">
            <!-- Back to Shared Scrapbook List -->
            <a href="{% url 'shared_scrapbook_list' %}" class="btn btn-info" aria-label="Go back to Shared Scrapbook List"><i class="fa-solid fa-arrow-left"></i></a>
            <br>
            <div class="row">
                <div class="mt-1 pt-3 col-sm-12 col-md-8">
                    <!-- Scrapbook title -->
                    <div class="col-sm-12 col-md-6">
                        <h3 class="d-inline">{{ scrapbook.title }}</h3>
                        <!-- Status icon conditionals -->
                        {% if scrapbook.status == 0 %}
                        <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-pen"></i></div>
                        {% elif scrapbook.status == 1 %}
                        <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-lock"></i></div>
                        {% elif scrapbook.status == 2 %}
                        <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-globe"></i></div>
                        {% endif %}
                    </div>
                    <!-- Scrapbook author | the scrapbook's created date goes after -->
                    <div class="col-sm-12 col-md-6">
                        <p class="scrapbook-subtitle d-inline">{{ scrapbook.author }} | </p>
                        <p class="scrapbook-subtitle d-inline">created on: {{ scrapbook.created_on }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- Post Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% if not sharedaccess and scrapbook.author != user and scrapbook.status != 2 %}
                <div class="col-12">
                    <div class="alert alert-danger" role="alert">
                        You do not have permission to view this scrapbook.
                    </div>
                </div>
                {% else %}
                {% for post in posts %}
                <!-- add cards for each post in this scrapbook -->
                <div id="post{{ post.id }}" class="col-md-6 col-lg-4" data-title="{{ post.title }}" data-content="{{ post.content }}" data-image-url="{% if post.images.all %}{{ post.images.all.0.featured_image.url }}{% endif %}">
                    <div class="card fixed-card mb-4">
                        <div class="text-center">
                            <img class="card-img-top" src="{{ post.image.url}}" alt="Image for the post titled '{{post.title}}'">
                        </div>
                        <div class="card-body px-3">
                            <div>
                            <!-- if user has shared access to the post, make the title a link -->
                                {% if post.id in shared_posts %}
                                <a class="text-decoration-none" href="{% url 'scrapbook:post_detail' scrapbook.slug post.slug %}" aria-label="Go to Post Detail page">
                                {% endif %}                                    
                                <h5 class="card-title d-inline {% if post.id in shared_posts %}linked-title{% endif %}">{{ post.title }}</h5>
                                {% if post.id in shared_posts %}
                                </a>
                                {% endif %}                                    
                                <!-- Status icon conditionals -->
                                {% if post.status == 0 %}
                                    <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-pen"></i></div>
                                {% elif post.status == 1 %}
                                    <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-lock"></i></div>
                                {% elif post.status == 2 %}
                                    <div class="card-text d-inline text-body-secondary"><i class="fa-solid fa-globe"></i></div>
                                {% endif %}
                                <!-- Last Updated -->
                                <p class="card-subtitle date-time mb-2">Updated: {{ post.updated_on }}</p>
                                <p class="card-text">{{ post.content|truncatechars:72|safe }}</p>
                            </div>
                            <div>
                                <!-- Open Button -->
                                <div class="d-grid gap-2 d-md-block text-center mb-1">
                                    <a href="{% url 'scrapbook:post_detail' scrapbook.slug post.slug %}" class="btn btn-info scrapbook-link " aria-label="Go to Post Detail page">Open <i class="fa-regular fa-image"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:6 %}
                </div>
                <div class="row">
                {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Pagination -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Go to previous page"> &laquo; PREV</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Go to next page"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock content %}